trytonus/trytond-shipping

shipment.py

The user can now use enter to go to next step

Make the continue buttons default

---

__init__.py
shipment.py
view/package_form.xml

Update to include 'box_type' field

---

shipment.py
view/package_form.xml

Add box dimensions fields to package

---

Makefile
shipment.py
tests/test_shipping.py

- Add test to check this behavior

Handle package weight redistribution

---

shipment.py

Inch is most common measurement unit for package so set
default to inch.

Set default on distance unit to inch

---

shipment.py
view/shipment_tracking_form.xml
view/shipment_tracking_tree.xml

Add 'state' to tracking numbers

---

shipment.py
shipment.xml
view/shipment_tracking_form.xml
view/shipment_tracking_tree.xml

- Add 'Refresh Status' button to tracking number

Add cron to refresh status of tracking numbers

---

manifest.xml

https://3.basecamp.com/3194017/buckets/421793/todos/121654070

Add Open and Closed tabs on shipping manifest view

---

carrier.xml
view/carrier_tree.xml

https://3.basecamp.com/3194017/buckets/421793/todos/123204149

Add active and closed tab on carrier

---

shipment.xml

https://3.basecamp.com/3194017/buckets/421793/todos/120566297

Remove redundant action menu item for label wizard

---

carrier.xml
configuration.py
manifest.xml
mixin.py
sale.xml
setup.py
shipment.py
tests/test_party.py
tests/test_shipping.py
tests/test_views_depends.py
tryton.cfg
view/generate_shipping_label_message_view_form.xml
view/generate_shipping_label_wizard_start_view_form.xml
view/no_module_form.xml
view/package_form.xml
view/party_configuration_form.xml

Migration to 4.0

---

mixin.py

https://sentry.fulfil.io/fulfilio/ln-production/group/3540/

Fix on_change_with_international_address

---

package.py

Hide dimensions when box type is given

---

mixin.py
tests/test_shipping.py

Prefer weight of packages for shipment over weight of outgoing moves

---

sale.py
tests/test_shipping.py

* Add test case to verify the result
[#132531299]

Reset order cache after adding shipping line

---

setup.py
shipment.py

Use simplejson instead of json

---

shipment.py

Convert datetime object to isoformat

---

package.py
shipment.py
tests/test_shipping.py
view/package_form.xml

Add override weight UOM field

---

carrier.py

Change 'Code' field on box type to readonly

---

mixin.py

Fix wrongly assigned value of cost_currency.
